### PR TITLE
grammatical error correction

### PR DESCRIPTION
**Pull request by Saksh8**
I have corrected the description of codechamp also added new terms to it for making it more impactful

### CODE REVIEW

**Comment by DeveloperAshish8** [comment]
Attach some images after edits for better understanding.

**Comment by Saksh8** [comment]
Screenshot_20221008-000129_Chrome

**Comment by Saksh8** [comment]
The code champ description needs improvement.
It is grammatical incorrect

**Comment by DeveloperAshish8** [comment]
Please solve the grammatical errors @Saksh8 .

**Pull request closed without merging**
