### PR TITLE
Footer updated

### PR DESCRIPTION
**Pull request by Shaliniyadav8130**
I added the social media icons on footer and also added the hover effect. I also update the background color of footer. please review it.
Screenshot (34)

### CODE REVIEW

**Comment by Shaliniyadav8130** [comment]
This orange color on Linkedln icon showing the color after hover on it.

**Comment by DeveloperAshish8** [comment]
Hey @Shaliniyadav8130 Can you please enhance the font of "Connect with me". Actually its looking odd in the website.

**Comment by Shaliniyadav8130** [comment]
Okk sir

**Comment by Shaliniyadav8130** [comment]
Sir I updated the footer section again and create a pull request again. So please review my work.

**Comment by Shaliniyadav8130** [comment]
Screenshot (35)

**Comment by DeveloperAshish8** [comment]
Sorry the issue is closed now and the UX of current icons seems good.

**Pull request closed without merging**
