### PR TITLE
Fixed error in dark mode while switching to internships/jobs page

### PR DESCRIPTION
**Pull request by bhoopesh369**

### CODE REVIEW

**Comment by bhoopesh369** [comment]
@DeveloperAshish8

**Comment by DeveloperAshish8** [comment]
Please share the video of after edits for better understanding.

**Comment by bhoopesh369** [comment]
Initially when we switch from home page to internships page the dark mode doesn't stay in dark mode ...it reverts back to normal mode

Now in my PR the dark mode stays in dark mode.

I hope this makes it clear .
@DeveloperAshish8

**Comment by bhoopesh369** [comment]
@DeveloperAshish8   You could now merge it

**Comment by DeveloperAshish8** [comment]
Great @bhoopesh369 ,
Thanks for your  contribution. Don't forget to join our discord server for more opportunities.

**Comment by bhoopesh369** [comment]
Heyy Thankyou

**Pull request merged**
