### PR TITLE
Scroll-Bar

### PR DESCRIPTION
**Pull request by Shaba1406**
# Description
- Improvement in Scroll Bar.
- Tech used :- CSS

Issue no. :- #72 

#Screenshots

|Screenshot 1|

- Display in white theme

CodeChamp - Google Chrome 10-10-2022 20_15_56

|Screenshot 2|

- Display in dark theme

CodeChamp - Google Chrome 10-10-2022 20_17_01

### CODE REVIEW

**Comment by DeveloperAshish8** [comment]
Hey @Shaba1406 , please resolve the conflict and make the color to orange as that of rest of elements for better UX.

**Comment by DeveloperAshish8** [comment]
Please update the image of new scroll bar look

**Comment by Shaba1406** [comment]
Done with it @DeveloperAshish8 .

**Comment by DeveloperAshish8** [comment]
Great @Shaba1406 , Thanks for you contribution.
Happy Coding ♥️.

**Pull request merged**
