### PR TITLE
Preloader Added

### PR DESCRIPTION
**Pull request by hamzailyas237**
I have added a preloader on both pages and it is working perfectly.

[screen-capture.webm](https://user-images.githubusercontent.com/65035919/194497100-d4b0f67d-58a7-46a1-83fd-39ee3960a559.webm)

### CODE REVIEW

**Comment by DeveloperAshish8** [comment]
Great work, Thanks for your contribution @hamzailyas237 

Happy coding ♥️.

**Comment by hamzailyas237** [comment]
@DeveloperAshish8 Welcome. I have noticed one thing now, on changing the page black color is blinking for a little time. I forgot to remove the background color from #preloader in style.css. just remove the background color black from it, then it will look more better.

**Comment by DeveloperAshish8** [comment]
The Preloader is even not responsive now .

**Comment by hamzailyas237** [comment]
I do not work on responsiveness. Wait I'm making it responsive.

**Pull request merged**
