### PR TITLE
Preloader added

### LINKED ISSUE #20: Adding entertaining preloader in the website 🧑‍💻
Please attach an image in the pull request if you are assigned for this issue.

### PR DESCRIPTION
**Pull request by divyanshraj0408**
### What I have done:
* Made a preloader following the ux_design_guidelines.
* Made the preloader responsive for all screens.
### Screenshots:
Screencast-from-02-10-22-09_24_33-PM-IST
Screenshot from 2022-10-02 21-18-15
Screenshot from 2022-10-02 21-18-05
Screenshot from 2022-10-02 21-17-57

ps: I have made some minor changes to make the loader a little better because the constrains which were given were fitting properly for the loader.
closes #20

### CODE REVIEW

**Comment by DeveloperAshish8** [comment]
Hey @divyanshraj0408 , the transition can be more smooth, please check out the gif provided.

**Comment by divyanshraj0408** [comment]
Screencast-from-02-10-22-11_19_21-PM-IST (1)
Due to conversion from .webm to .gif in this gif, the animation seems a little longer but it ends in 2 seconds only, I have tried to make the transition more smoother by using opacity, please suggest if any other method can be used.

**Comment by divyanshraj0408** [comment]
> Previous one was good but the time between code and learn is a little less as compared to learn and grow.
This was happening because of the time delay for starting the loader and also because of uneven distribution of time between every change. I have fixed this, hope it works :+1:

**Comment by DeveloperAshish8** [comment]
Please attach the video after fixing.

**Comment by divyanshraj0408** [comment]
chrome-capture-2022-9-4 (1)

**Comment by DeveloperAshish8** [comment]
Hey @divyanshraj0408 , please check the guidelines care, the order should be Code, learn and then grow and your video is stating code, grow and then learn

**Comment by divyanshraj0408** [comment]
Okay, will change that, is everything else fine?

**Comment by DeveloperAshish8** [comment]
Yes @divyanshraj0408 , overall ok but please increase the time a little more.

**Comment by divyanshraj0408** [comment]
chrome-capture-2022-9-4 (3)

**Comment by DeveloperAshish8** [comment]
Resolve the conflicts.

**Comment by divyanshraj0408** [comment]
done

**Comment by DeveloperAshish8** [comment]
Yes Finally it's done , Thanks @divyanshraj0408 for contributing to our website.

Happy coding ♥️.

**Pull request merged**
