### PR TITLE
Fixes issue #143

### PR DESCRIPTION
**Pull request by Vedant-Manjrekar**
Made changes so that when website shifts to Dark-Mode Logo color of Github Changes from black to white in order to improve visibility of the logo.

### CODE REVIEW

**Comment by DeveloperAshish8** [comment]
Please add the screenshot here as well @Vedant-Manjrekar .

**Comment by Vedant-Manjrekar** [comment]
Before:
Screenshot 2022-10-15 at 8 51 55 PM
Screenshot 2022-10-15 at 8 53 43 PM

**Comment by DeveloperAshish8** [comment]
Great @Vedant-Manjrekar ,
Thanks for your contribution ♥️.

Don't forget to join us on our Discord server for more Opportunities.

**Comment by Vedant-Manjrekar** [comment]
> Great @Vedant-Manjrekar , Thanks for your contribution ♥️.
> 
> Don't forget to join us on our Discord server for more Opportunities.

You are most Welcome @DeveloperAshish8 and it was great working with you.
Surely i will join the discord server.

**Pull request merged**
