### PR TITLE
Modified form placeholder

### PR DESCRIPTION
**Pull request by irapandey**
I have modified the contact form to make the placeholder vanish when OnClick is heard and recover when focus is out.

### CODE REVIEW

**Comment by DeveloperAshish8** [comment]
please add some screenshots of the changes you have done

**Comment by irapandey** [comment]
Pardon the watermark.
You can see how the placeholder disappears when the focus is on the input and re-appears when the focus is off

Uploading codechamp-placeholder-demo.mp4…

**Comment by irapandey** [comment]
https://user-images.githubusercontent.com/69388190/195382116-7c0b1495-6861-421d-8b3f-32f66515ae90.mp4

**Comment by DeveloperAshish8** [comment]
I think it's not doing any major changes @irapandey , please have a look on other issues @irapandey .

**Pull request closed without merging**
