### PR TITLE
Improving the 'Why to join us?' section

### PR DESCRIPTION
**Pull request by Saloni098**
issue #148

### CODE REVIEW

**Comment by DeveloperAshish8** [comment]
please add some screenshots of after edits.

**Comment by Saloni098** [comment]
Yes sure!

**Comment by Saloni098** [comment]
Screenshot 2022-10-18 185922


Screenshot 2022-10-18 190040

**Comment by Saloni098** [comment]
Thanks, @DeveloperAshish8, happy to contribute. Looking forward to learning and contributing more to the community😀

**Pull request merged**
