### PR TITLE
updated scroll to top button

### PR DESCRIPTION
**Pull request by Muhammad235**
updated the scroll to top button so that it shows on scroll and the user is aware of how long they have scrolled

### CODE REVIEW

**Comment by DeveloperAshish8** [comment]
please share the video or gif after edits here as well.

**Comment by Muhammad235** [comment]
@https://user-images.githubusercontent.com/101328329/197783203-bd2f5559-ea7d-430e-8156-fdf9d444c202.mp4

**Comment by Muhammad235** [comment]
@DeveloperAshish8 please check out the video of the new added feature

**Comment by DeveloperAshish8** [comment]
Great @Muhammad235 , Thanks for making us better.
Happy Coding ❤️.

Don't forgot to join us on our discord server for more opportunities.

**Comment by DeveloperAshish8** [comment]
Please have a look @Muhammad235 , I think its not working

**Comment by Muhammad235** [comment]
@DeveloperAshish8 it is working, upload it and let me see it live

**Comment by DeveloperAshish8** [comment]
Uploaded and cross checked in chrome and Firefox not working

**Comment by Muhammad235** [comment]
It is working well on my laptop and I made a video of that, I want to check if I have pushed it to the forked repo

**Pull request merged**
