### PR TITLE
Dark mode feature added

### PR DESCRIPTION
**Pull request by Aman-0604**
@DeveloperAshish8 your website looks awesome in dark mode ! See from the below screenshots :

# 1
Screenshot 2022-10-02 at 2 04 20 AM

# 2
Screenshot 2022-10-02 at 2 05 03 AM

# 3
Screenshot 2022-10-02 at 2 05 37 AM

### CODE REVIEW

**Comment by Aman-0604** [comment]
@DeveloperAshish8 please merge the pull request under the` hacktoberfest` tag as it was a good task in which quality javascript logic has to be written.

**Comment by DeveloperAshish8** [comment]
Hey @Aman-0604 , can you please enhance the design of the button for switching from dark to light mode for better understanding.

**Comment by Aman-0604** [comment]
Hey @DeveloperAshish8 , now check I have enhanced the design of the button for better understanding.

# Here is the screenshot for the same : 
Screenshot 2022-10-02 at 11 05 38 AM

**Comment by DeveloperAshish8** [comment]
Great @Aman-0604 , Now it's looking good. Thanks for your contribution to our project. 

Happy Coding ♥️.

**Pull request merged**
